app <- ShinyDriver$new("../", shinyOptions = list(display.mode = "normal"))
Sys.sleep(2)
app$snapshotInit("mytest")
Sys.sleep(2)
app$snapshot()
Sys.sleep(2)
app$setInputs(ex5_visible = TRUE)
Sys.sleep(2)
app$snapshot()
Sys.sleep(2)
app$snapshot()
