app <- ShinyDriver$new("../", seed = 100,shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(individual_obs = TRUE)
app$setInputs(density = TRUE)
app$snapshot()
app$setInputs(bw_adjust = 2)
app$snapshot()
app$setInputs(bw_adjust = 0.2)
app$setInputs(bw_adjust = 2)
app$snapshot()
app$setInputs(bw_adjust = 0.2)
app$snapshot()
app$setInputs(n_breaks = "50")
app$snapshot()
