app <- ShinyDriver$new("../", shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(dataset = "pressure")
app$snapshot()
app$setInputs(dataset = "cars")
app$snapshot()
app$snapshotDownload("downloadData")
app$snapshot()
app$setInputs(dataset = "rock")
app$snapshot()
app$setInputs(dataset = "pressure")
