app <- ShinyDriver$new("../", seed = 100,shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(type = "educat")
app$snapshot()
app$setInputs(type = "unempl")
app$snapshot()
app$setInputs(type = "travel")
app$snapshot()
app$setInputs(smoother = TRUE)
app$snapshot()
app$setInputs(f = 0.08)
app$snapshot()
app$setInputs(f = 1)
app$snapshot()
app$setInputs(date = c("2007-01-01", "2017-07-13"))
app$snapshot()
app$setInputs(date = c("2007-01-01", "2017-07-01"))
app$snapshot()
app$snapshot()
