app <- ShinyDriver$new("../", shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")
app$snapshot()
app$setInputs(x = "hp")
app$snapshot()
app$setInputs(x = "carb")
app$snapshot()
app$snapshot()
app$setInputs(x = "qsec")
app$snapshot()
app$setInputs(x = "drat")
app$snapshot()
app$setInputs(x = "vs")
app$snapshot()
