app <- ShinyDriver$new("../", seed = 100,shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")
Sys.sleep(5)
app$snapshot()
app$setInputs(x = "hp")
Sys.sleep(5)
app$snapshot()
app$setInputs(x = "carb")
Sys.sleep(5)
app$snapshot()
Sys.sleep(5)
app$snapshot()
app$setInputs(x = "qsec")
Sys.sleep(5)
app$snapshot()
app$setInputs(x = "drat")
Sys.sleep(5)
app$snapshot()
app$setInputs(x = "vs")
Sys.sleep(5)
app$snapshot()
