app <- ShinyDriver$new("../", shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(insertBtn = "click")
app$snapshot()
app$setInputs(insertBtn = "click")
app$setInputs(insertBtn = "click")
app$setInputs(insertBtn = "click")
app$setInputs(insertBtn = "click")
app$snapshot()
app$setInputs(removeBtn = "click")
app$setInputs(removeBtn = "click")
app$snapshot()
app$setInputs(removeBtn = "click")
app$setInputs(removeBtn = "click")
app$snapshot()
