#!/usr/bin/Rscript

if (FALSE) {
  devtools::install_github('rstudio/shiny')
  devtools::install_github('rstudio/shinyapps')
}

# first, sync shiny examples
if (file_test('-d', '../shiny/inst/examples')) {
  for (app in list.dirs('../shiny/inst/examples', recursive = FALSE)) {
    dir.create(app1 <- sub('^(\\d\\d)_', '0\\1-', basename(app)), showWarnings = FALSE)
    file.copy(list.files(app, full.names = TRUE), app1, recursive = TRUE)
    writeLines(
      sub('^License: .+$', 'License: MIT', readLines(file.path(app, 'DESCRIPTION'))),
      file.path(app1, 'DESCRIPTION')
    )
  }
}

# then deploy all apps
library(methods)
library(shinyapps)
apps = list.dirs(full.names = FALSE, recursive = FALSE)
apps = grep('^[0-9]{3,}', apps, value = TRUE)
for (app in apps) {
  deployApp(app)
}
