#!/usr/bin/Rscript

# first, sync shiny examples
if (file_test('-d', '../shiny/inst/examples')) {
  for (app in list.dirs('../shiny/inst/examples', recursive = FALSE))
    file.copy(app, './', recursive = TRUE)
}

# then deploy all apps
library(methods)
library(shinyapps)
apps = list.dirs(full.names = FALSE, recursive = FALSE)
apps = grep('^[0-9]{2,}', apps, value = TRUE)
for (app in apps) {
  deployApp(app)
  writeLines(
    sprintf(c('# %s', '', 'Live demo: <http://demo.shinyapps.io/%s>'), app),
    file.path(app, 'README.md')
  )
}
