app <- ShinyDriver$new("../", seed = 100,shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(deepstacktrace = TRUE)
app$snapshot()
app$setInputs(success = "click")
app$snapshot()
app$setInputs(failure = "click")
app$snapshot()
app$setInputs(success = "click")
app$setInputs(success = "click")
app$setInputs(success = "click")
