app <- ShinyDriver$new("../../", seed = 100)
app$snapshotInit("mytest")

Sys.sleep(10)
app$snapshot()

Sys.sleep(10)
app$snapshot()
app$setInputs(`plot1_vars-xvar` = "Total_Bsmt_SF")
app$setInputs(`plot1_vars-yvar` = "Mas_Vnr_Area")
app$setInputs(`plot1_vars-groupvar` = "Roof_Style")
app$setInputs(`plot2_vars-xvar` = "Total_Bsmt_SF")

Sys.sleep(10)
app$snapshot()
app$setInputs(`plot2_vars-yvar` = "Garage_Area")

Sys.sleep(10)
app$snapshot()
Sys.sleep(10)
app$setInputs(`plot2_vars-groupvar` = "Overall_Cond")
Sys.sleep(10)
app$snapshot()
Sys.sleep(10)
app$snapshot()
Sys.sleep(10)
app$snapshot()
app$setInputs(`plot2_vars-xvar` = "Lot_Frontage")
Sys.sleep(10)
app$snapshot()
