app <- ShinyDriver$new("../", seed = 100,shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(n = 680)
app$snapshot()
app$setInputs(n = 1000)
app$snapshot()
app$setInputs(n = 460)
app$setInputs(n = 500)
app$snapshot()
app$setInputs(n = 70)
app$snapshot()
app$setInputs(n = 790)
app$snapshot()
app$setInputs(n = 890)
app$snapshot()
app$setInputs(n = 900)
app$snapshot()
