app <- ShinyDriver$new("../", shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(num = 0)
app$setInputs(num = 1)
app$setInputs(num = 2)
app$setInputs(num = 3)
app$setInputs(num = 4)
app$setInputs(num = 5)
app$snapshot()
app$setInputs(num = 6)
app$setInputs(num = 7)
app$setInputs(num = 8)
app$setInputs(num = 9)
app$setInputs(num = 10)
app$snapshot()
app$setInputs(num = 11)
app$setInputs(num = 12)
app$setInputs(num = 13)
app$setInputs(num = 14)
app$setInputs(num = 15)
app$snapshot()
