app <- ShinyDriver$new("../", seed = 100,shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(duration = "5")
app$snapshot()
app$setInputs(duration = "10")
app$snapshot()
app$setInputs(type = "message")
app$setInputs(show = "click")
app$snapshot()
app$setInputs(txt = "Text of messagemnvckns")
app$setInputs(show = "click")
app$setInputs(remove = "click")
app$snapshot()
app$setInputs(type = "error")
app$setInputs(close = FALSE)
app$snapshot()
