app <- ShinyDriver$new("../", seed = 100,shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(n = 100)
app$setInputs(n = 120)
app$snapshot()
app$setInputs(n = 60)
app$snapshot()
app$setInputs(n = 160)
app$snapshot()
