app <- ShinyDriver$new("../index.Rmd", seed = 8296, shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(asp = 0.3)
app$snapshot()
app$setInputs(asp = 0.02)
app$setInputs(asp = 0.3)
app$setInputs(asp = 0.02)
app$snapshot()
app$setInputs(asp = 0.156)
app$snapshot()
app$setInputs(size = 3.25)
app$setInputs(size = 5)
app$snapshot()
app$setInputs(size = 0.2)
app$snapshot()
app$setInputs(size = 2.15)
app$snapshot()
app$setInputs(size = 3.8)
app$snapshot()
