app <- ShinyDriver$new("../", seed = 100,shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$snapshot()
app$snapshot()
app$snapshot()
app$snapshot()
app$snapshot()
app$setInputs(rateThreshold = 31.9)
app$snapshot()
app$setInputs(maxrows = 26)
app$setInputs(maxrows = 27)
app$setInputs(maxrows = 28)
app$setInputs(maxrows = 29)
app$setInputs(maxrows = 30)
app$snapshot()
app$snapshot()
