app <- ShinyDriver$new("../", shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$setInputs(format = 5000)
app$snapshot()
app$setInputs(decimal = 1)
app$snapshot()
app$setInputs(integer = 167)
app$snapshot()
app$setInputs(range = c(200, 861))
app$snapshot()
app$setInputs(format = 10000)
app$snapshot()
app$setInputs(format = 5000)
app$snapshot()
app$setInputs(animation = 851)
app$snapshot()
app$setInputs(range = c(1, 861))
app$setInputs(range = c(1, 1))
app$snapshot()
app$setInputs(format = 7500)
app$setInputs(format = 0)
app$snapshot()
