app <- ShinyDriver$new("../", seed = 100,shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$snapshot()
app$snapshot()
app$snapshot()
app$setInputs(decimal = 1)
app$setInputs(integer = 32)
app$snapshot()
app$setInputs(range = c(200, 972))
app$snapshot()
app$setInputs(range = c(584, 972))
app$snapshot()
app$setInputs(format = 5000)
app$snapshot()
app$setInputs(format = 10000)
app$snapshot()
app$setInputs(animation = 631)
app$snapshot()
app$setInputs(animation = 1691)
app$snapshot()
app$setInputs(animation = 2000)
app$snapshot()
