app <- ShinyDriver$new("../", seed = 100,shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")
Sys.sleep(5)
app$snapshot()
app$setInputs(input_type = "text")
Sys.sleep(5)
app$snapshot()
app$setInputs(input_type = "numeric")
Sys.sleep(5)
app$snapshot()
app$setInputs(input_type = "checkbox")
Sys.sleep(5)
app$snapshot()
app$setInputs(input_type = "checkboxGroup")
Sys.sleep(5)
app$snapshot()
app$setInputs(input_type = "radioButtons")
Sys.sleep(5)
app$snapshot()
app$setInputs(input_type = "selectInput")
Sys.sleep(5)
app$snapshot()
app$setInputs(input_type = "selectInput (multi)")
Sys.sleep(5)
app$snapshot()
app$setInputs(input_type = Sys.Date(),wait_=FALSE, values_=FALSE)
Sys.sleep(5)
app$snapshot()
app$setInputs(input_type = "daterange")
Sys.sleep(5)
app$snapshot()
app$setInputs(dynamic = c("2018-04-20", "2018-04-16"))
Sys.sleep(5)
app$snapshot()
app$setInputs(input_type = "slider")
app$setInputs(dynamic = 20)
Sys.sleep(5)
app$snapshot()
app$setInputs(dynamic = 10)
Sys.sleep(5)
app$snapshot()
app$setInputs(input_type = "checkbox")
app$setInputs(dynamic = FALSE)
Sys.sleep(5)
app$snapshot()
app$setInputs(dynamic = TRUE)
Sys.sleep(5)
app$snapshot()
app$setInputs(input_type = "radioButtons")
app$setInputs(dynamic = "option1")
Sys.sleep(5)
app$snapshot()
Sys.sleep(5)
app$setInputs(dynamic = "option2")
Sys.sleep(5)
app$snapshot()
app$setInputs(input_type = "date")
app$setInputs(dynamic = "2018-04-07")
Sys.sleep(5)
app$snapshot()
