app <- ShinyDriver$new("../", shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(input_type = "text")
app$snapshot()
app$setInputs(input_type = "numeric")
app$snapshot()
app$setInputs(input_type = "checkbox")
app$snapshot()
app$setInputs(input_type = "checkboxGroup")
app$snapshot()
app$setInputs(input_type = "radioButtons")
app$snapshot()
app$setInputs(input_type = "selectInput")
app$snapshot()
app$setInputs(input_type = "selectInput (multi)")
app$snapshot()
app$setInputs(input_type = "date")
app$snapshot()
app$setInputs(input_type = "daterange")
app$snapshot()
app$setInputs(dynamic = c("2018-04-20", "2018-04-16"))
app$snapshot()
app$setInputs(input_type = "slider")
app$setInputs(dynamic = 20)
app$snapshot()
app$setInputs(dynamic = 10)
app$snapshot()
app$setInputs(input_type = "checkbox")
app$setInputs(dynamic = FALSE)
app$snapshot()
app$setInputs(dynamic = TRUE)
app$snapshot()
app$setInputs(input_type = "radioButtons")
app$setInputs(dynamic = "option1")
app$snapshot()
app$setInputs(dynamic = "option2")
app$snapshot()
app$setInputs(input_type = "date")
app$setInputs(dynamic = "2018-04-07")
app$snapshot()
