app <- ShinyDriver$new("../", seed = 100,shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(checkGroup = c("1", "2"))
app$snapshot()
app$setInputs(checkGroup = c("1", "2", "3"))
app$snapshot()
app$setInputs(checkGroup = c("2", "3"))
app$snapshot()
app$setInputs(checkGroup = "3")
app$snapshot()
app$setInputs(checkGroup = character(0))
app$snapshot()
app$setInputs(checkGroup = "1")
app$setInputs(checkGroup = c("1", "2"))
app$setInputs(checkGroup = c("1", "2", "3"))
app$snapshot()
