app <- ShinyDriver$new("../", shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$uploadFile(file1 = "Rock.csv") # <-- This should be the path to the file, relative to the app's tests/ directory
app$snapshot()
app$setInputs(sep = ";")
app$setInputs(sep = ",")
app$setInputs(quote = "")
app$snapshot()
app$setInputs(sep = ";")
app$snapshot()
app$setInputs(sep = "	")
app$snapshot()
app$setInputs(disp = "all")
app$snapshot()
app$setInputs(quote = "'")
app$snapshot()
app$snapshot()
app$snapshot()
app$setInputs(disp = "head")
app$snapshot()
