app <- ShinyDriver$new("../", shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(`plot1-n` = 180)
app$snapshot()
app$setInputs(`plot2-n` = 190)
app$snapshot()
app$setInputs(`plot2-n` = 200)
app$snapshot()
app$setInputs(`plot2-n` = 20)
app$snapshot()
app$setInputs(`plot1-n` = 40)
app$snapshot()
app$setInputs(`plot1-n` = 10)
app$snapshot()
app$setInputs(`plot2-n` = 10)
app$snapshot()
