app <- ShinyDriver$new("../", shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(x = "clarity")
app$setInputs(sampleSize = 27001)
app$setInputs(jitter = TRUE)
app$snapshot()
app$setInputs(smooth = TRUE)
app$snapshot()
app$setInputs(y = "depth")
app$snapshot()
app$snapshot()
app$setInputs(facet_row = "clarity")
app$snapshot()
app$setInputs(facet_col = "color")
app$snapshot()
app$setInputs(sampleSize = 32001)
app$setInputs(sampleSize = 32501)
app$snapshot()
app$setInputs(sampleSize = 4501)
app$snapshot()
app$setInputs(jitter = FALSE)
app$snapshot()
app$setInputs(facet_col = "clarity")
app$snapshot()
app$setInputs(color = "cut")
app$setInputs(y = "color")
app$setInputs(sampleSize = 35001)
app$setInputs(jitter = TRUE)
app$setInputs(smooth = FALSE)
