app <- ShinyDriver$new("../../", seed = 100)
app$snapshotInit("mytest")

app$setInputs(`server-1-select` = "1")
app$setInputs(`server-2-select` = "1")
app$setInputs(`server-3-select` = "1")
app$setInputs(`server-4-select` = "1")
app$setInputs(`server-5-select` = "1")
app$setInputs(`server-6-select` = "1")
app$setInputs(`server-8-select` = "a1")
app$setInputs(`server-9-select` = "a1")
app$setInputs(`server-10-select` = "a1")
app$setInputs(`server-11-select` = "a1")
app$setInputs(`server-12-select` = "a1")
app$snapshot()
app$setInputs(`client-1-select` = "2")
app$setInputs(`server-1-select` = "2")
app$setInputs(`client-2-select` = "2")
app$setInputs(`server-2-select` = "2")
app$setInputs(`client-3-select` = "2")
app$setInputs(`server-3-select` = "2")
app$setInputs(`client-4-select` = "2")
app$setInputs(`server-4-select` = "2")
app$setInputs(`client-5-select` = "2")
app$setInputs(`server-5-select` = "2")
app$setInputs(`client-6-select` = "3")
app$setInputs(`server-6-select` = "3")
app$setInputs(`client-7-select` = "2")
app$setInputs(`server-7-select` = "2")
app$setInputs(`server-8-select` = "a4")
app$setInputs(`server-9-select` = "a5")
app$setInputs(`server-10-select` = "a5")
app$setInputs(`server-11-select` = "a6")
app$setInputs(`server-12-select` = "a2")
app$setInputs(`server-13-select` = "2")
app$snapshot()
