app <- ShinyDriver$new("../", seed = 100,shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")
Sys.sleep(2)
app$snapshot()
app$setInputs(xcol = "Petal.Length")
Sys.sleep(2)
app$snapshot()
app$setInputs(ycol = "Petal.Length")
Sys.sleep(2)
app$snapshot()
app$setInputs(clusters = 4)
app$setInputs(clusters = 5)
app$setInputs(clusters = 6)
app$setInputs(clusters = 7)
app$setInputs(clusters = 8)
app$setInputs(clusters = 9)
Sys.sleep(2)
app$snapshot()
app$setInputs(ycol = "Petal.Width")
Sys.sleep(2)
app$snapshot()
app$setInputs(xcol = "Species")
Sys.sleep(2)
app$snapshot()
