app <- ShinyDriver$new("../", shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")
Sys.sleep(1)
app$snapshot()
app$setInputs(plot_type = "column")
Sys.sleep(1)
app$snapshot()
app$setInputs(theme = "chalk")
app$setInputs(theme = "fivethirtyeight")
Sys.sleep(2)
app$snapshot()
