app <- ShinyDriver$new("../", seed = 100,shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(type = "error")
app$snapshot()
app$setInputs(type = "silent")
app$snapshot()
app$setInputs(type = "validation")
app$snapshot()
app$setInputs(success = "click")
app$snapshot()
app$setInputs(error = "click",wait_=FALSE, values_=FALSE)
app$snapshot()
