app <- ShinyDriver$new("../", seed = 100,shinyOptions = list(display.mode = "normal"))
Sys.sleep(2)
app$snapshotInit("mytest")
Sys.sleep(2)
app$snapshot()
app$setInputs(sineAmplitude = -1.5)
Sys.sleep(2)
app$snapshot()
app$setInputs(sineAmplitude = -0.1)
Sys.sleep(2)
app$snapshot()
app$setInputs(sinePhase = 100)
Sys.sleep(2)
app$snapshot()
app$setInputs(sinePhase = 180)
app$setInputs(sinePhase = -140)
Sys.sleep(2)
app$snapshot()
