app <- ShinyDriver$new("../", seed = 100,shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(r = 0.7)
app$snapshot()
app$setInputs(picture = "face")
app$snapshot()
app$setInputs(r = 1)
app$snapshot()
app$setInputs(r = 0.35)
app$setInputs(r = 0.05)
app$snapshot()
app$setInputs(r = 0.25)
app$snapshot()
app$setInputs(picture = "chainring")
app$snapshot()
