app <- ShinyDriver$new("../../", seed = 100)
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(palette = "magma")
app$setInputs(bins = 6)
app$setInputs(bins = 8)
app$snapshot()
app$setInputs(palette = "Blues")
app$setInputs(bins = 9)
app$setInputs(bins = 10)
app$setInputs(bins = 11)
app$setInputs(bins = 12)
app$snapshot()
app$setInputs(reverse = TRUE)
app$snapshot()
app$setInputs(palette = "Reds")
app$snapshot()
app$setInputs(palette = "Accent")
app$snapshot()
app$setInputs(palette = "Paired")
app$snapshot()
