app <- ShinyDriver$new("../", seed = 100,shinyOptions = list(display.mode = "normal"))
Sys.sleep(2)
app$snapshotInit("mytest")
Sys.sleep(2)
app$snapshot()
Sys.sleep(2)
app$snapshot()
Sys.sleep(2)
app$snapshot()
Sys.sleep(2)
app$snapshot()
Sys.sleep(2)
app$snapshot()
Sys.sleep(2)
app$snapshot()
