app <- ShinyDriver$new("../", seed = 100,shinyOptions = list(display.mode = "normal"))
Sys.sleep(3)
app$snapshotInit("mytest")
Sys.sleep(3)
app$snapshot()
app$setInputs(dist = "unif")
Sys.sleep(3)
app$snapshot()
Sys.sleep(3)
app$snapshot()
Sys.sleep(3)
app$snapshot()
app$setInputs(dist = "lnorm")
Sys.sleep(3)
app$snapshot()
app$setInputs(dist = "exp")
Sys.sleep(3)
app$snapshot()
Sys.sleep(3)
app$snapshot()
app$setInputs(dist = "norm")
Sys.sleep(3)
app$snapshot()
app$setInputs(n = 1)
app$setInputs(n = 1000)
Sys.sleep(3)
app$snapshot()
app$setInputs(n = 1)
app$setInputs(n = 107)
app$setInputs(n = 1)
Sys.sleep(3)
app$snapshot()
app$setInputs(n = 511)
Sys.sleep(3)
app$snapshot()
app$setInputs(n = 896)
Sys.sleep(3)
app$snapshot()
