app <- ShinyDriver$new("../", shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(dist = "unif")
app$snapshot()
app$snapshot()
app$snapshot()
app$setInputs(dist = "lnorm")
app$snapshot()
app$setInputs(dist = "exp")
app$snapshot()
app$snapshot()
app$setInputs(dist = "norm")
app$snapshot()
app$setInputs(n = 1)
app$setInputs(n = 1000)
app$snapshot()
app$setInputs(n = 1)
app$setInputs(n = 107)
app$setInputs(n = 1)
app$snapshot()
app$setInputs(n = 511)
app$snapshot()
app$setInputs(n = 896)
app$snapshot()
