app <- ShinyDriver$new("../", seed = 100,shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(n = 760)
app$snapshot()
app$setInputs(n = 120)
app$setInputs(goButton = "click")
app$setInputs(n = 790)
app$snapshot()
app$setInputs(goButton = "click")
app$setInputs(n = 60)
app$snapshot()
app$setInputs(goButton = "click")
app$snapshot()
