app <- ShinyDriver$new("../", seed = 100,shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest2")

app$setInputs(action = "click")
app$setInputs(action = "click")
app$setInputs(action = "click")
app$setInputs(action = "click")
app$setInputs(checkbox = FALSE)
app$setInputs(checkbox = TRUE)
app$setInputs(checkbox = FALSE)
app$setInputs(checkbox = TRUE)
app$snapshot()
app$setInputs(checkGroup = character(0))
app$setInputs(checkGroup = "2")
app$setInputs(checkGroup = c("2", "3"))
app$snapshot()
app$setInputs(checkGroup = "2")
app$setInputs(checkGroup = character(0))
app$setInputs(checkGroup = "1")
app$snapshot()
app$setInputs(checkGroup = character(0))
app$snapshot()
app$setInputs(checkbox = FALSE)
app$snapshot()
app$setInputs(checkbox = TRUE)
app$snapshot()
app$setInputs(date = "2014-01-15")
app$setInputs(date = "2014-01-30")
app$snapshot()
app$setInputs(dates = c("2019-12-19", "2019-12-05"))
app$snapshot()
app$setInputs(dates = c("2019-12-19", "2019-12-12"))
app$snapshot()
app$uploadFile(file = "cars.csv") # <-- This should be the path to the file, relative to the app's tests/shinytests directory
app$setInputs(select = "3")
app$setInputs(slider1 = 18)
app$setInputs(slider1 = 71)
app$setInputs(select = "2")
app$setInputs(select = "1")
app$snapshot()
app$setInputs(radio = "2")
app$snapshot()
app$setInputs(radio = "3")
app$snapshot()
app$setInputs(slider1 = 31)
app$snapshot()
app$setInputs(slider1 = 79)
app$snapshot()
app$setInputs(slider2 = c(0, 75))
app$snapshot()
app$setInputs(slider2 = c(0, 100))
app$snapshot()
app$setInputs(text = "hsgdfhjg")
app$snapshot()
