app <- ShinyDriver$new("../", seed = 100,shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")
Sys.sleep(5)
app$snapshot()
app$setInputs(text = "Enter ")
app$setInputs(text = "Enter hagjhfafglak")
Sys.sleep(5)
app$snapshot()
app$setInputs(slider2 = c(25, 87))
app$setInputs(slider2 = c(69, 87))
Sys.sleep(5)
app$snapshot()
app$setInputs(slider1 = 100)
app$setInputs(checkGroup = c("1", "2"))
app$setInputs(checkGroup = c("1", "2", "3"))
Sys.sleep(5)
app$snapshot()
app$setInputs(checkbox = FALSE)
Sys.sleep(5)
app$snapshot()
app$setInputs(action = "click")
app$setInputs(action = "click")
Sys.sleep(5)
app$snapshot()
