app <- ShinyDriver$new("../", shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(text = "Enter ")
app$setInputs(text = "Enter hagjhfafglak")
app$snapshot()
app$setInputs(slider2 = c(25, 87))
app$setInputs(slider2 = c(69, 87))
app$snapshot()
app$setInputs(slider1 = 100)
app$setInputs(checkGroup = c("1", "2"))
app$setInputs(checkGroup = c("1", "2", "3"))
app$snapshot()
app$setInputs(checkbox = FALSE)
app$snapshot()
app$setInputs(action = "click")
app$setInputs(action = "click")
app$snapshot()
