app <- ShinyDriver$new("../", shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(freq = 35)
app$snapshot()
app$setInputs(freq = 1)
app$snapshot()
app$setInputs(max = 1)
app$setInputs(max = 300)
app$setInputs(max = 1)
app$snapshot()
app$setInputs(max = 300)
app$snapshot()
app$setInputs(selection = "merchant")
app$snapshot()
app$setInputs(selection = "romeo")
app$snapshot()
app$setInputs(update = "click")
app$setInputs(freq = 43)
app$snapshot()
