app <- ShinyDriver$new("../", shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(variable = "am")
app$snapshot()
app$setInputs(variable = "gear")
app$snapshot()
app$setInputs(outliers = FALSE)
app$snapshot()
app$setInputs(variable = "cyl")
app$snapshot()
app$setInputs(variable = "am")
app$snapshot()
app$setInputs(variable = "cyl")
app$snapshot()
