app <- ShinyDriver$new("../", shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(action = "click")
app$snapshot()
app$setInputs(action = "click")
app$snapshot()
app$setInputs(action = "click")
app$snapshot()
app$setInputs(action = "click")
app$snapshot()
