app <- ShinyDriver$new("../", shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(vars = "渗透性")
app$snapshot()
app$setInputs(obs = 4)
app$setInputs(obs = 5)
app$setInputs(obs = 6)
app$setInputs(obs = 7)
app$setInputs(obs = 8)
app$snapshot()
app$setInputs(dataset = "cars")
app$snapshot()
app$setInputs(dataset = "pressure")
app$snapshot()
app$setInputs(summary = FALSE)
app$snapshot()
