app <- ShinyDriver$new("../../", seed = 100)
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(progress = "click")
app$snapshot()
app$setInputs(dates = c("2000-01-19", "2018-02-01"))
app$setInputs(dates = c("2000-01-19", "2018-01-31"))
app$setInputs(progress = "click")
app$snapshot()
app$setInputs(`._bookmark_` = "click")
app$setInputs(sidebarCollapsed = TRUE)
app$snapshot()
app$setInputs(sidebarCollapsed = FALSE)
app$snapshot()
