app <- ShinyDriver$new("../", shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")
Sys.sleep(1)
app$snapshot()
app$setInputs(`shinytheme-selector` = "lumen")
Sys.sleep(1)
app$snapshot()
app$snapshot()
app$snapshot()
app$setInputs(txt = "general ")
app$setInputs(txt = "general test")
app$setInputs(txt = "general testing")
app$setInputs(action2 = "click")
app$snapshot()
app$uploadFile(file = "Rock.csv") # <-- This should be the path to the file, relative to the app's tests/ directory
app$setInputs(action2 = "click")
app$snapshot()
app$setInputs(slider = 75)
app$setInputs(slider = 100)
app$snapshot()
app$setInputs(action = "click")
app$setInputs(`shinytheme-selector` = "spacelab")
Sys.sleep(1)
app$snapshot()
app$setInputs(`shinytheme-selector` = "yeti")
Sys.sleep(1)
app$snapshot()
app$setInputs(slider = 1)
app$setInputs(slider = 100)
app$setInputs(slider = 79)
Sys.sleep(1)
app$snapshot()
