app <- ShinyDriver$new("../", seed = 100,shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(format = "HTML")
app$snapshot()
app$setInputs(format = "Word")
app$snapshot()
app$setInputs(format = "PDF")
app$setInputs(x = "disp")
app$snapshot()
app$setInputs(x = "drat")
app$snapshot()
app$setInputs(x = "carb")
app$snapshot()
app$setInputs(x = "gear")
app$snapshot()
app$setInputs(x = "qsec")
app$snapshot()
app$setInputs(format = "Word")
app$setInputs(x = "vs")
app$snapshotDownload("downloadReport")
