library(shinytest)
app <- ShinyDriver$new("../", shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(dataset = "pressure")
app$snapshot()
app$setInputs(dataset = "cars")
app$setInputs(obs = 11)
app$setInputs(obs = 12)
app$setInputs(obs = 13)
app$snapshot()
app$setInputs(obs = 12)
app$setInputs(obs = 13)
app$setInputs(obs = 14)
app$setInputs(obs = 15)
app$setInputs(obs = 16)
app$setInputs(obs = 17)
app$setInputs(obs = 18)
app$snapshot()
app$setInputs(obs = 19)
app$setInputs(obs = 20)
app$setInputs(obs = 21)
app$setInputs(obs = 20)
app$setInputs(obs = 19)
app$setInputs(obs = 18)
app$setInputs(obs = 17)
app$setInputs(obs = 16)
app$setInputs(obs = 15)
app$setInputs(obs = 14)
app$setInputs(obs = 13)
app$setInputs(obs = 12)
app$setInputs(obs = 11)
app$setInputs(obs = 10)
app$setInputs(obs = 9)
app$setInputs(obs = 8)
app$setInputs(obs = 7)
app$setInputs(obs = 6)
app$setInputs(obs = 5)
app$setInputs(obs = 4)
app$setInputs(obs = 3)
app$setInputs(obs = 2)
app$setInputs(obs = 1)
app$setInputs(obs = 0)
app$setInputs(obs = -1)
app$setInputs(obs = -2)
app$setInputs(obs = -3)
app$setInputs(obs = -4)
app$setInputs(obs = -5)
app$setInputs(obs = -6)
app$setInputs(obs = -7)
app$setInputs(obs = -8)
app$setInputs(obs = -9)
app$setInputs(obs = -10)
app$setInputs(obs = -11)
app$setInputs(obs = -12)
app$setInputs(obs = -13)
app$setInputs(obs = -14)
app$setInputs(obs = -15)
app$setInputs(obs = -16)
app$setInputs(obs = -17)
app$setInputs(obs = -18)
app$setInputs(obs = -19)
app$setInputs(obs = -20)
app$setInputs(obs = -21)
app$setInputs(obs = -22)
app$setInputs(obs = -23)
app$setInputs(obs = -24)
app$setInputs(obs = -25)
app$setInputs(obs = -26)
app$setInputs(obs = -27)
app$setInputs(obs = -28)
app$setInputs(obs = -29)
app$snapshot()
app$snapshot()
app$setInputs(dataset = "pressure")
app$snapshot()
app$setInputs(dataset = "rock")
app$setInputs(dataset = "cars")
app$setInputs(dataset = "pressure")
app$setInputs(dataset = "rock")
app$snapshot()
