app <- ShinyDriver$new("../../", seed = 100)
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(decimal = 1)
app$snapshot()
app$setInputs(range = c(200, 1000))
app$setInputs(format = 7500)
app$setInputs(animation = 1051)
app$snapshot()
app$setInputs(format = 0)
app$snapshot()
app$setInputs(range = c(200, 727))
app$setInputs(decimal = 0.3)
app$snapshot()
app$setInputs(integer = 32)
app$setInputs(integer = 37)
app$snapshot()
app$setInputs(format = 7500)
app$snapshot()
app$setInputs(animation = 2000)
app$snapshot()
