app <- ShinyDriver$new("../", shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(style = "old")
app$setInputs(goPlot = "click")
app$setInputs(goTable = "click")
app$snapshot()
app$setInputs(style = "notification")
app$setInputs(goPlot = "click")
app$snapshot()
app$setInputs(style = "old")
app$setInputs(goTable = "click")
app$snapshot()
