app <- ShinyDriver$new("../", seed = 100,shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(in1 = "Alaska")
app$setInputs(in1 = "California")
app$setInputs(in2 = "Arkansas")
app$setInputs(in3 = "Alabama")
app$setInputs(in3 = "Alaska")
app$setInputs(in3 = "Arizona")
app$setInputs(in3 = "Alabama")
app$setInputs(in3 = "Arkansas")
app$setInputs(in6 = "Arizona")
app$setInputs(in6 = c("Arizona", "California"))
app$setInputs(in6 = c("Arizona", "California", "Connecticut"))
app$setInputs(in5 = "Arkansas")
app$setInputs(in4 = "Arkansas")
app$snapshot()
