app <- ShinyDriver$new("../../", seed = 100)
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(simpleTextInput = "f")
app$setInputs(simpleTextInput = "fg")
app$setInputs(simpleTextInput = "fgg")
app$setInputs(simpleTextInput = "fggh")
app$setInputs(simpleTextInput = "fgghj")
app$setInputs(simpleTextInput = "fgghjg")
app$setInputs(simpleTextInput = "fgghjgj")
app$setInputs(simpleTextInput = "fgghjgjk")
app$setInputs(simpleTextInput = "fgghjgjkg")
app$setInputs(simpleTextInput = "fgghjgjkgu")
app$snapshot()
app$setInputs(`._bookmark_` = "click")
app$snapshot()
app$snapshot()
