app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$setInputs(set = "Named vector")
app$snapshot()
app$snapshot()
app$setInputs(set = "Partially named vector")
app$snapshot()
app$setInputs(set = "Unnamed list")
app$snapshot()
app$setInputs(set = "Named list")
app$snapshot()
app$setInputs(set = "Partially named list")
app$snapshot()
app$setInputs(set = "Nested list")
app$snapshot()
app$setInputs(s_select = "3")
app$snapshot()
app$setInputs(m_select = "3")
app$snapshot()
app$setInputs(m_select = c("3", "5"))
app$snapshot()
app$setInputs(server = TRUE)
app$setInputs(s_select = "1")
app$snapshot()
app$setInputs(s_select = "3")
app$snapshot()
app$setInputs(m_select = "3")
app$snapshot()
app$setInputs(m_select = c("3", "5"))
app$snapshot()
app$setInputs(set = "Big unnamed list (server-side only)")
app$setInputs(s_select = "a1")
app$snapshot()
app$setInputs(set = "Big nested list (server-side only)")
app$setInputs(s_select = "a1")
app$snapshot()
app$setInputs(s_select = "a2")
app$snapshot()
app$setInputs(m_select = "a1")
app$setInputs(m_select = c("a1", "a2"))
app$snapshot()
app$setInputs(set = "Unnamed vector")
app$setInputs(s_select = "1")
app$setInputs(server = FALSE)
app$setInputs(selected = TRUE)
app$snapshot()
app$setInputs(server = TRUE)
app$setInputs(s_select = "2")
app$snapshot()
app$setInputs(set = "Named vector")
app$setInputs(s_select = "2")
app$setInputs(m_select = "2")
app$snapshot()
app$setInputs(server = FALSE)
app$snapshot()
