app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(selected = TRUE)
app$snapshot()
app$setInputs(selected = FALSE)
app$setInputs(set = "Named vector")
app$snapshot()
app$setInputs(selected = TRUE)
app$snapshot()
app$setInputs(selected = FALSE)
app$setInputs(set = "Partially named vector")
app$snapshot()
app$setInputs(s_select = "3")
app$snapshot()
app$setInputs(selected = TRUE)
app$snapshot()
app$setInputs(set = "Unnamed list")
app$snapshot()
app$setInputs(selected = FALSE)
app$snapshot()
app$setInputs(set = "Named list")
app$snapshot()
app$setInputs(selected = TRUE)
app$snapshot()
app$setInputs(selected = FALSE)
app$setInputs(set = "Partially named list")
app$snapshot()
app$setInputs(s_select = "3")
app$snapshot()
app$setInputs(selected = TRUE)
app$setInputs(set = "Nested list")
app$setInputs(selected = FALSE)
app$snapshot()
app$setInputs(s_select = "5")
app$snapshot()
app$setInputs(selected = TRUE)
app$snapshot()
app$setInputs(selected = FALSE)
app$setInputs(set = "Nested list (with vectors)")
app$snapshot()
app$setInputs(s_select = "5")
app$snapshot()
app$setInputs(selected = TRUE)
app$snapshot()
app$setInputs(selected = FALSE)
app$setInputs(set = "Unnamed vector")
app$setInputs(server = TRUE)
app$setInputs(s_select = "1")
app$snapshot()
app$setInputs(set = "Named vector")
app$setInputs(s_select = "1")
app$snapshot()
app$setInputs(selected = TRUE)
app$snapshot()
app$setInputs(set = "Partially named vector")
app$setInputs(s_select = "2")
app$setInputs(m_select = "2")
app$setInputs(selected = FALSE)
app$setInputs(s_select = "1")
app$snapshot()
app$setInputs(s_select = "3")
app$snapshot()
app$setInputs(selected = TRUE)
app$snapshot()
app$setInputs(selected = FALSE)
app$setInputs(set = "Unnamed list")
app$setInputs(s_select = "1")
app$snapshot()
app$setInputs(selected = TRUE)
app$setInputs(s_select = "2")
app$snapshot()
app$setInputs(selected = FALSE)
app$setInputs(set = "Named list")
app$snapshot()
app$setInputs(selected = TRUE)
app$snapshot()
app$setInputs(selected = FALSE)
app$setInputs(set = "Partially named list")
app$setInputs(s_select = "1")
app$snapshot()
app$setInputs(s_select = "3")
app$snapshot()
app$setInputs(selected = TRUE)
app$snapshot()
app$setInputs(set = "Nested list")
app$setInputs(s_select = "2")
app$setInputs(selected = FALSE)
app$setInputs(s_select = "1")
app$snapshot()
app$setInputs(s_select = "5")
app$snapshot()
app$setInputs(selected = TRUE)
app$setInputs(s_select = "2")
app$setInputs(m_select = "2")
app$snapshot()
app$setInputs(selected = FALSE)
app$setInputs(s_select = "1")
app$setInputs(set = "Nested list (with vectors)")
app$setInputs(s_select = "1")
app$snapshot()
app$setInputs(s_select = "5")
app$snapshot()
app$setInputs(selected = TRUE)
app$snapshot()
app$setInputs(selected = FALSE)
app$setInputs(s_select = "1")
app$setInputs(set = "Big unnamed vector (server-side only)")
app$setInputs(s_select = "a1")
app$snapshot()
app$setInputs(set = "Big named vector (server-side only)")
app$setInputs(s_select = "a1")
app$snapshot()
app$setInputs(set = "Big unnamed list (server-side only)")
app$setInputs(s_select = "a1")
app$snapshot()
app$setInputs(set = "Big named list (server-side only)")
app$setInputs(s_select = "a1")
app$snapshot()
app$setInputs(set = "Big nested list (server-side only)")
app$setInputs(s_select = "a1")
app$snapshot()
app$setInputs(m_select = "a1")
app$setInputs(m_select = c("a1", "a2"))
app$setInputs(m_select = c("a1", "a2", "a3"))
app$snapshot()
