app <- ShinyDriver$new("../../", seed = 100)
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(update = "click")
app$snapshot()
app$setInputs(update = "click")
app$snapshot()
app$snapshot()
app$setInputs(checkboxGroupInput1 = "a")
app$snapshot()
app$setInputs(varSelectInput1 = "Petal.Width")
app$setInputs(update = "click")
app$snapshot()
