app <- ShinyDriver$new("../", seed = 100,shinyOptions = list(display.mode = "normal"))
Sys.sleep(5)
app$snapshotInit("mytest")
Sys.sleep(5)
app$snapshot()
app$setInputs(a2 = "T")
Sys.sleep(5)
app$snapshot()
app$setInputs(a5 = "T")
Sys.sleep(5)
app$snapshot()
app$setInputs(a2 = "N",wait_=FALSE, values_=FALSE)
Sys.sleep(5)
app$snapshot()
app$setInputs(a1 = "U")
Sys.sleep(5)
app$snapshot()
