app <- ShinyDriver$new("../", seed = 100,shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(choice = "b",wait_=FALSE,values_=FALSE)
app$snapshot()
app$setInputs(go = "click",wait_=FALSE,values_=FALSE)
app$snapshot()
app$setInputs(choice = "c",wait_=FALSE,values_=FALSE)
app$setInputs(go = "click",wait_=FALSE,values_=FALSE)
app$snapshot()
app$setInputs(choice = "b",wait_=FALSE,values_=FALSE)
app$setInputs(go = "click",wait_=FALSE,values_=FALSE)
app$snapshot()
