app <- ShinyDriver$new("../../", seed = 100)
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(click = "click")
app$setInputs(click = "click")
app$setInputs(click = "click")
app$setInputs(click = "click")
app$setInputs(click = "click")
app$setInputs(click = "click")
app$setInputs(click = "click")
app$snapshot()
app$setInputs(click = "click")
app$setInputs(click = "click")
app$snapshot()
