app <- ShinyDriver$new("../", seed = 100,shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$snapshot()
app$snapshotDownload("downloadData")
app$setInputs(filetype = "tsv")
app$snapshot()
app$snapshotDownload("downloadData")
app$setInputs(dataset = "Pressure")
app$snapshot()
app$setInputs(dataset = "Cars")
app$snapshot()
app$setInputs(filetype = "csv")
app$snapshot()
