library(shinytest)
app <- ShinyDriver$new("../", shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(bins = 50)
app$snapshot()
app$setInputs(bins = 35)
app$setInputs(bins = 32)
app$setInputs(bins = 31)
app$setInputs(bins = 30)
app$snapshot()
app$setInputs(bins = 1)
app$setInputs(bins = 3)
app$setInputs(bins = 50)
app$snapshot()
app$setInputs(bins = 21)
app$snapshot()
app$setInputs(bins = 50)

app$snapshot()
