app <- ShinyDriver$new("../../", seed = 100)
app$snapshotInit("mytest")

app$setInputs(n = 20)
app$snapshot()
app$setInputs(n = 32)
app$snapshot()
app$snapshot()
app$setInputs(n = 8)
app$snapshot()
app$setInputs(n = 24)
app$snapshot()
app$setInputs(n = 8)
app$snapshot()
app$setInputs(n = 28)
app$setInputs(n = 32)
app$snapshot()
app$setInputs(n = 16)
app$snapshot()
app$setInputs(n = 20)
app$snapshot()
