app <- ShinyDriver$new("../", shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(n = 200)
app$snapshot()
app$setInputs(n = 80)
app$setInputs(n = 130)
app$setInputs(n = 50)
app$snapshot()
app$setInputs(n = 200)
app$snapshot()
app$setInputs(n = 10)
app$snapshot()
app$setInputs(n = 110)
app$setInputs(n = 100)
app$snapshot()
