app <- ShinyDriver$new("../../", seed = 100)
app$snapshotInit("mytest")

app$setInputs(dataset = "titanic")
app$setInputs(tabs_data = "View")
app$setInputs(tabs_data = "Visualize")
app$setInputs(tabs_data = "Manage")
app$setInputs(dman_preview = "str")
app$snapshot()
app$setInputs(dman_preview = "preview")
app$snapshot()
app$setInputs(dman_preview = "summary")
app$snapshot()
app$setInputs(dataType = "clipboard")
app$snapshot()
app$setInputs(dataType = "url_rds")
app$snapshot()
app$setInputs(saveAs = "csv")
app$snapshot()
app$setInputs(tabs_data = "View")
app$snapshot()
app$snapshot()
app$snapshot()
app$snapshot()
app$setInputs(view_dec = 1)
app$setInputs(view_dec = 2)
app$setInputs(view_dec = 3)
app$setInputs(view_dec = 5)
app$setInputs(view_store = "click")
app$snapshot()
app$snapshot()
app$setInputs(tabs_data = "Visualize")
app$setInputs(dataset = "diamonds")
app$setInputs(viz_run = "click")
app$setInputs(viz_type = "scatter")
app$snapshot()
app$setInputs(viz_nrobs = "-1")
app$snapshot()
app$setInputs(viz_yvar = "price")
app$setInputs(viz_yvar = c("price", "carat"))
app$setInputs(viz_yvar = c("price", "carat", "depth"))
app$snapshot()
app$setInputs(viz_xvar = "carat")
app$setInputs(viz_xvar = c("carat", "clarity"))
app$setInputs(viz_xvar = c("carat", "clarity", "cut"))
app$snapshot()
app$setInputs(viz_color = "cut")
app$setInputs(viz_size = "carat")
app$snapshot()
app$setInputs(viz_fun = "median")
app$snapshot()
app$setInputs(viz_check = "line")
app$setInputs(viz_check = c("line", "loess"))
app$snapshot()
app$setInputs(viz_smooth = 2.3)
app$snapshot()
app$snapshot()
app$setInputs(tabs_data = "Pivot")
app$setInputs(pvt_run = "click")
app$setInputs(tabs_data = "Explore")
app$snapshot()
app$setInputs(tabs_data = "Transform")
app$snapshot()
app$setInputs(tabs_data = "Combine")
app$snapshot()
