app <- ShinyDriver$new("../", shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(slider2 = c(40, 100))
app$setInputs(slider2 = c(40, 95))
app$snapshot()
app$setInputs(slider1 = 72)
app$snapshot()
app$setInputs(slider1 = 90)
app$snapshot()
app$setInputs(slider2 = c(40, 65))
app$setInputs(slider2 = c(16, 65))
app$snapshot()
