app <- ShinyDriver$new("../", seed = 100,shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(color1 = "click")
app$snapshot()
app$setInputs(message = "click")
app$setInputs(message = "click")
app$snapshot()
app$setInputs(busy = "click")
app$snapshot()
app$setInputs(end = "click",wait_=FALSE, values_=FALSE)
app$snapshot()
