app <- ShinyDriver$new("../", shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(dataset = "cars")
app$snapshot()
app$setInputs(format = "bordered")
app$setInputs(format = c("striped", "bordered"))
app$snapshot()
app$setInputs(align = "cc")
app$snapshot()
app$setInputs(align = "NULL")
app$setInputs(rownames = "T")
app$snapshot()
