app <- ShinyDriver$new("../", seed = 100,shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(e0 = "California")
app$snapshot()
app$setInputs(e3 = "Arizona")
app$setInputs(e5 = "Colorado")
app$setInputs(e5 = c("Colorado", "Connecticut"))
app$setInputs(e6 = "Arkansas")
app$setInputs(e7 = "Arizona")
app$snapshot()
app$snapshot()
app$setInputs(e2 = "California")
app$snapshot()
app$setInputs(e4 = "Arizona")
app$snapshot()
app$snapshot()
