app <- ShinyDriver$new("../", shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$setInputs(go = "click")
app$snapshot()
app$setInputs(n = 51)
app$setInputs(n = 52)
app$setInputs(n = 53)
app$setInputs(n = 54)
app$setInputs(n = 55)
app$setInputs(n = 56)
app$setInputs(n = 57)
app$setInputs(n = 58)
app$setInputs(n = 59)
app$setInputs(n = 60)
app$setInputs(n = 61)
app$setInputs(n = 62)
app$setInputs(n = 63)
app$setInputs(n = 64)
app$setInputs(n = 65)
app$setInputs(n = 66)
app$setInputs(n = 67)
app$setInputs(n = 68)
app$snapshot()
app$setInputs(go = "click")
app$snapshot()
