app <- ShinyDriver$new("../../", seed = 100)
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(x = 10)
app$snapshot()
app$setInputs(reset = "click")
app$snapshot()
app$setInputs(`._bookmark_` = "click")
app$snapshot()
app$setInputs(x = 9)
app$setInputs(`._bookmark_` = "click")
app$snapshot()
app$setInputs(reset = "click")
