app <- ShinyDriver$new("../", shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(control_num = 8)
app$setInputs(inDateRange = c("2013-01-08", "2013-12-15"))
app$setInputs(inDateRange = c("2013-01-08", "2013-12-08"))
app$snapshot()
app$setInputs(inNumber = 8.5)
app$setInputs(inNumber = 9)
app$setInputs(inNumber = 9.5)
app$setInputs(inNumber = 10)
app$snapshot()
app$setInputs(inSlider = 20)
app$snapshot()
app$setInputs(inSlider2 = c(7, 20))
app$snapshot()
app$setInputs(inCheckboxGroup = c("option-8-A", "option-8-B"))
app$setInputs(inCheckboxGroup = "option-8-B")
app$setInputs(inSelect = "option-8-B")
app$snapshot()
app$setInputs(inTabset = "panel2")
app$snapshot()
