app <- ShinyDriver$new("../", shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$setInputs(go = "click")
app$snapshot()
app$setInputs(go = "click")
app$setInputs(unifRange = c(-10, 100))
app$snapshot()
app$setInputs(go = "click")
app$snapshot()
app$setInputs(tabset = "Normal")
app$snapshot()
app$setInputs(go = "click")
app$snapshot()
app$setInputs(normMean = 1)
app$setInputs(normMean = 2)
app$setInputs(normMean = 3)
app$setInputs(normMean = 4)
app$snapshot()
app$snapshot()
