app <- ShinyDriver$new("../../", seed = 100)
app$snapshotInit("mytest")

app$setInputs(inc = "click")
app$setInputs(inc = "click")
app$setInputs(inc = "click")
app$snapshot()
app$setInputs(`one-inc` = "click")
app$setInputs(`one-inc` = "click")
app$setInputs(`one-inc` = "click")
app$setInputs(`one-inc` = "click")
app$setInputs(`one-inc` = "click")
app$setInputs(`one-inc` = "click")
app$snapshot()
app$setInputs(`one-inc` = "click")
app$setInputs(`one-inc` = "click")
app$setInputs(inc = "click")
app$setInputs(inc = "click")
app$setInputs(inc = "click")
app$snapshot()
